### ISSUE TITLE
Doesn't work vscode.dev or code-server

### ISSUE THREAD

**Issue by bilogic** [g-plane/vscode-beefweb#1]
![image](https://github.com/g-plane/vscode-beefweb/assets/946010/f604c4dd-b9be-4735-9873-c485cadd3580)

Hi, I have been looking for something like this for the longest time!

But it doesn't work in vscode.dev or code-server. Able to help find the cause?

Thank you!

**Comment by g-plane** [comment]
This extension uses Node.js "http" and "events" module, but it may be able to be refactored to be platform-independent.

**Comment by bilogic** [comment]
Haha thanks for getting back! VSCode plugins are unfamiliar terrority for me.

**Comment by g-plane** [comment]
I found that beefweb doesn't support CORS, so it can't be accessed in browsers though this extension can be run on browsers.

**Comment by g-plane** [comment]
Published v0.6.1. You can try it now.

**Comment by bilogic** [comment]
Hi, thanks!

I still get the same issue 
![image](https://github.com/g-plane/vscode-beefweb/assets/946010/ac0eb673-4d16-41cb-a34a-1b4c55644f06)

**Comment by g-plane** [comment]
Can you provide more detail, such as information from browsers Developer Tools?

**Comment by bilogic** [comment]
I don't really know what to provide actually, but let me try in a bit. Thank you.

**Comment by bilogic** [comment]
![image](https://github.com/g-plane/vscode-beefweb/assets/946010/be1b395c-4ed4-4153-b50e-9d9fd7b47a54)

i think i found the issue

**Comment by g-plane** [comment]
That's a limitation from browsers.

**Comment by bilogic** [comment]
possible to configure this extension to support https and allow me to specify username and password for `/api/player/next`?

**Comment by g-plane** [comment]
It's possible.

**Comment by g-plane** [comment]
v0.7.0 is published. You can configure URL in `beefweb.server.url` setting.
